ryan-xin/week05/Day03/epl-teams/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ----------------------------------- TEAM ----------------------------------- #

  # CREATE
  get "/teams/new" => "teams#new", as: "new_team"

  post "/teams" => "teams#create"


  # READ
  get "/teams" => "teams#index"

  get "/teams/:id" => "teams#show", as: "/team"


  # UPDATE
  get "/teams/:id/edit" => "teams#edit", as: "edit_team"
  
  patch "/teams/:id" => "teams#update"


  # DESTROY
  delete "/teams/:id" => "teams#destroy"


  # ---------------------------------- PLAYERS --------------------------------- #

  resources :players













end

ryan-xin/week05/Day03/epl-teams/app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team,
  optional: true
end

ryan-xin/week05/Day03/epl-teams/app/models/team.rb
class Team < ApplicationRecord
  has_many :players
end

ryan-xin/week05/Day03/epl-teams/app/controllers/players_controller.rb
class PlayersController < ApplicationController

  # CREATE
  def new
    @player = Player.new
  end

  def create
    Player.create player_params
    redirect_to(players_path)
  end


  # READ
  def index
    @players = Player.all
  end

  def show
    @player = Player.find params[:id]
  end


  # UPDATE
  def edit
    @player = Player.find params[:id]
  end

  def update
    player = Player.find params[:id]
    player.update player_params
    redirect_to(player_path(params[:id]))
  end


  # DESTROY
  def destroy
    Player.destroy params[:id]
    redirect_to(players_path)
  end

  
  private

  def player_params
    params.require(:player).permit(:name, :nationality, :age, :position, :number, :team_id)
  end
  
end

ryan-xin/week05/Day03/epl-teams/app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  # CREATE
  def new
    @team = Team.new
  end
  
  def create
    Team.create team_params
    redirect_to(teams_path)
  end
    

  # READ
  def index
    @teams = Team.all
    @team = Team.new
  end
  
  def show
    @team = Team.find params[:id]
  end
  
  
  # UPDATE
  def edit
    @team = Team.find params[:id]
  end

  def update
    team = Team.find params[:id]
    team.update team_params

    team.players << Player.find(params[:player_ids])

    redirect_to(team_path(params[:id]))
  end


  # DESTROY
  def destroy
    Team.destroy params[:id]
    redirect_to(teams_path)
  end
  

  private

  def team_params
    params.require(:team).permit(:name, :founded, :stadium, :logo, :manager, :ucl)
  end
  
  
  
end

ryan-xin/week05/Day03/epl-teams/app/helpers/players_helper.rb
module PlayersHelper
end

ryan-xin/week05/Day03/epl-teams/app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  
  <%= f.label :nationality %><br>
  <%= f.text_field :nationality %><br>
  
  <%= f.label :age %><br>
  <%= f.text_field :age %><br>
  
  <%= f.label :position %><br>
  <%= f.text_field :position %><br>
  
  <%= f.label :number %><br>
  <%= f.text_field :number %><br>
  
  <%= f.label :team_id, "Select Team" %><br>
  <%= f.select :team_id, Team.pluck(:name, :id) %><br>

  <%= f.submit %>

<% end %>

ryan-xin/week05/Day03/epl-teams/app/views/players/edit.html.erb
<h2>Edit <%= @player.name %></h2>

<%= render partial: "form" %>

ryan-xin/week05/Day03/epl-teams/app/views/players/index.html.erb
<h2>All Players</h2>

<ul>
  <% @players.each do |player| %>
    <li><%= link_to player.name, player_path(player.id) %></li>  
  <% end %>
</ul>

<p><button data-micromodal-trigger="modal-1">Click here to open the modal!</button></p>

<div class="modal micromodal-slide" id="modal-1" aria-hidden="true">
  <div class="modal__overlay" tabindex="-1" data-micromodal-close>
    <div class="modal__container" role="dialog" aria-modal="true" aria-labelledby="modal-1-title">
      <header class="modal__header">
        <h2 class="modal__title" id="modal-1-title">
          Micromodal
        </h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
      </header>
      <main class="modal__content" id="modal-1-content">
        <p>
        Try hitting the <code>tab</code> key and notice how the focus stays within the modal itself. Also, <code>esc</code> to close modal.
        </p>
      </main>
      <footer class="modal__footer">
        <button class="modal__btn modal__btn-primary">Continue</button>
        <button class="modal__btn" data-micromodal-close aria-label="Close this dialog window">Close</button>
      </footer>
    </div>
  </div>
</div>

ryan-xin/week05/Day03/epl-teams/app/views/players/new.html.erb
<h2>Add New Player</h2>

<%= render partial: "form" %>

ryan-xin/week05/Day03/epl-teams/app/views/players/show.html.erb
<h2><%= @player.name %></h2>

<nav class="edit">
  <li><%= link_to "Edit", edit_player_path(@player.id) %></li>
  <li><%= link_to "Delete", player_path(@player.id), method: "delete" %></li>
</nav>

<p>Nationality:</p>
<h4><%= @player.nationality %></h4>

<p>Age:</p>
<h4><%= @player.age %></h4>

<p>Position:</p>
<h4><%= @player.position %></h4>

<p>Number:</p>
<h4><%= @player.number %></h4>

<p>Team:</p>
<h4><%= link_to @player.team.name, team_path(@player.team.id) %></h4>