karthikeyan-sekar/week5/tue/homework/rails-islands/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # CREATE
  get '/islands/new' => 'islands#new'

  post '/islands' => 'islands#create'
  # READ
  get '/islands' => 'islands#index'
  get '/islands/:id' => 'islands#show', as: 'island'
  # UPDATE
  get '/islands/:id/edit' => 'islands#edit', as: 'island_edit'
  post '/islands/:id' => 'islands#update'
  # DESTROY
  get '/islands/:id/destroy' => 'islands#destroy', as: 'island_destroy'
end

karthikeyan-sekar/week5/tue/homework/rails-islands/app/models/island.rb
class Island < ApplicationRecord

end

karthikeyan-sekar/week5/tue/homework/rails-islands/app/controllers/islands_controller.rb
class IslandsController < ApplicationController

skip_before_action :verify_authenticity_token, raise: false

def new
end

def create
  Island.create(
    name: params[:name],
    image: params[:image],
    population: params[:population],
    area: params[:area],
    currency: params[:currency]
  )

  redirect_to(islands_path)
end
def index
  @islands = Island.all
end
def show
@island = Island.find params[:id]
end
def edit
@island = Island.find params[:id]
end
def update
  island = Island.find params[:id]
  island.update(
    name: params[:name],
    image: params[:image],
    population: params[:population],
    area: params[:area],
    currency: params[:currency]
  )

  redirect_to(island_path(params[:id]))
end
def destroy
  Island.destroy params[:id]
  redirect_to(islands_path)

end
end

karthikeyan-sekar/week5/tue/homework/rails-islands/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIslands</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>World of Islands</h1>
<nav>
<a href="<%= islands_path %>">Index</a>
<a href="<%= islands_new_path %>">Add Island</a>

</nav>
    <hr>
      <%= yield %>
      <hr>
    <footer>
      @copyright WorldTourism 2020
    </footer>
  </body>
</html>